---
layout: post
title: Django reset database connection
tags: django postgres
---

<p>
Django handles database connections transparently in almost all cases. It will <a href="https://docs.djangoproject.com/en/dev/ref/databases/#transaction-handling">start a new connection</a> when your request starts up, and commit it at the end of the request lifetime. Other times you need to dive in further and do your own granular <a href="https://docs.djangoproject.com/en/dev/topics/db/transactions/">transaction management</a>. But for the most part, it's fully automatic.
</p>

<p>
However, sometimes your use case may require that you close the current database connection and open a new one. While this is possible in Django, it's <a href="http://stackoverflow.com/questions/1303654/threaded-django-task-doesnt-automatically-handle-transactions-or-db-connections">not well documented</a>.
</p>

<p>
Why would you want to do this? I my case, I was writing an automation test framework. Some of the automation tests make database calls through the Django ORM to setup records, clean up after the test, etc. Each test is executed in the same process space, via a thread pool. We found that if one of the early tests threw an unrecoverable database error, such as an <a href="https://code.djangoproject.com/wiki/IntegrityError">IntegrityError</a> due to violating a unique constraint, the database connection would be aborted. Subsequent tests that tried to use the database would raise a <a href="https://docs.djangoproject.com/en/1.2/ref/exceptions/#django.db.DatabaseError">DatabaseError</a>:
</p>

<pre name="code" class="python">
Traceback (most recent call last):
  File /home/user/project/app/test.py, line 73, in tearDown
    MyModel.objects.all()
  File /usr/local/lib/python2.6/dist-packages/django/db/models/query.py, line 444, in delete
    collector.collect(del_query)
  File /usr/local/lib/python2.6/dist-packages/django/db/models/deletion.py, line 146, in collect
    reverse_dependency=reverse_dependency)
  File /usr/local/lib/python2.6/dist-packages/django/db/models/deletion.py, line 91, in add
    if not objs:
  File /usr/local/lib/python2.6/dist-packages/django/db/models/query.py, line 113, in __nonzero__
    iter(self).next()
  File /usr/local/lib/python2.6/dist-packages/django/db/models/query.py, line 107, in _result_iter
    self._fill_cache()
  File /usr/local/lib/python2.6/dist-packages/django/db/models/query.py, line 772, in _fill_cache
    self._result_cache.append(self._iter.next())
  File /usr/local/lib/python2.6/dist-packages/django/db/models/query.py, line 273, in iterator
    for row in compiler.results_iter():
  File /usr/local/lib/python2.6/dist-packages/django/db/models/sql/compiler.py, line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File /usr/local/lib/python2.6/dist-packages/django/db/models/sql/compiler.py, line 735, in execute_sql
    cursor.execute(sql, params)
  File /usr/local/lib/python2.6/dist-packages/django/db/backends/postgresql_psycopg2/base.py, line 44, in execute
    return self.cursor.execute(query, args)
DatabaseError: server closed the connection unexpectedly
 This probably means the server terminated abnormally
 before or while processing the request.
</pre>

<p>
It turns out that it's relatively easy to reset the database connection. We just called the following function at the start of every test. Django is smart enough to re-initialize the connection the next time it's used, assuming that it's disconnected properly.
</p>

<pre name="code" class="python">
def reset_database_connection():
    from django import db
    db.close_connection()
</pre>
